import { afterEach, expect, it, vi } from 'vitest'
import { createVoiceCalls } from './calls'
import { a, b, FakeCall, fakeAudio, fakePort, fakeStream } from './testing/fakes'

afterEach(() => vi.useRealTimers())
it('starts one call for a pair, attaches one stream, and drops stale callbacks', () => {
  const { port, calls } = fakePort()
  const { audio, releases } = fakeAudio()
  const state = vi.fn()
  const manager = createVoiceCalls({ port, audio, self: a, onState: state })
  manager.reconcile([a, b])
  manager.reconcile([a, b])
  expect(calls).toHaveLength(1)
  const stream = fakeStream()
  calls[0].emit({ type: 'stream', stream })
  calls[0].emit({ type: 'stream', stream })
  calls[0].emit({ type: 'ice', state: 'connected' })
  expect(audio.attach).toHaveBeenCalledOnce()
  expect(state).toHaveBeenLastCalledWith({ readyMemberIds: ['b'], failedMemberIds: [] })
  manager.reconcile([a])
  expect(calls[0].close).toHaveBeenCalledOnce()
  expect(releases[0]).toHaveBeenCalledOnce()
  calls[0].emit({ type: 'stream', stream })
  expect(audio.attach).toHaveBeenCalledOnce()
  manager.dispose()
})
it('rejects pre-roster calls, wrong metadata and duplicates without answering', () => {
  const { port, deliver } = fakePort()
  const { audio } = fakeAudio()
  const manager = createVoiceCalls({ port, audio, self: b, onState: vi.fn() })
  const unknown = new FakeCall('pa', { version: 1, callerSessionId: 'va', calleeSessionId: 'vb' })
  deliver(unknown)
  expect(unknown.close).toHaveBeenCalledOnce()
  expect(unknown.answer).not.toHaveBeenCalled()
  manager.reconcile([a, b])
  const old = new FakeCall('pa', { version: 1, callerSessionId: 'old', calleeSessionId: 'vb' })
  deliver(old)
  expect(old.close).toHaveBeenCalledOnce()
  const current = new FakeCall('pa', { version: 1, callerSessionId: 'va', calleeSessionId: 'vb' })
  deliver(current)
  current.ready()
  expect(current.answer).toHaveBeenCalledOnce()
  const duplicate = new FakeCall('pa', current.metadata)
  deliver(duplicate)
  expect(duplicate.close).toHaveBeenCalledOnce()
  expect(duplicate.answer).not.toHaveBeenCalled()
  manager.dispose()
})
it('marks setup timeout, retries only the initiator, and cancels departed peers', async () => {
  vi.useFakeTimers()
  const { port, calls } = fakePort()
  const state = vi.fn()
  const manager = createVoiceCalls({ port, audio: fakeAudio().audio, self: a, onState: state })
  manager.reconcile([a, b])
  await vi.advanceTimersByTimeAsync(15000)
  expect(state).toHaveBeenLastCalledWith({ readyMemberIds: [], failedMemberIds: ['b'] })
  await vi.advanceTimersByTimeAsync(3000)
  expect(calls).toHaveLength(2)
  calls[1].ready()
  manager.reconcile([a])
  await vi.advanceTimersByTimeAsync(90000)
  expect(calls).toHaveLength(2)
  manager.dispose()
  expect(vi.getTimerCount()).toBe(0)
})
it('lets a transient ICE disconnect recover before a new dial and replaces all senders', async () => {
  vi.useFakeTimers()
  const { port, calls } = fakePort()
  const manager = createVoiceCalls({ port, audio: fakeAudio().audio, self: a, onState: vi.fn() })
  manager.reconcile([a, b])
  calls[0].ready()
  calls[0].emit({ type: 'ice', state: 'disconnected' })
  await vi.advanceTimersByTimeAsync(1000)
  calls[0].emit({ type: 'ice', state: 'connected' })
  await vi.advanceTimersByTimeAsync(10000)
  expect(calls).toHaveLength(1)
  const track = fakeStream().getAudioTracks()[0]
  await manager.replaceTrack(track)
  expect(calls[0].replaceTrack).toHaveBeenCalledWith(track)
  calls[0].replaceTrack.mockRejectedValueOnce(new Error('cannot replace'))
  await manager.replaceTrack(track)
  await vi.advanceTimersByTimeAsync(3000)
  expect(calls).toHaveLength(2)
  manager.dispose()
})
