import { afterEach, expect, it, vi } from 'vitest'
import { createRetryScheduler } from './reconnect'

afterEach(() => vi.useRealTimers())
it('waits grace then retries five times and never retries an exhausted generation', async () => {
  vi.useFakeTimers()
  const scheduler = createRetryScheduler()
  const attempt = vi.fn().mockResolvedValue(false)
  scheduler.start('pair', attempt)
  scheduler.start('pair', attempt)
  await vi.advanceTimersByTimeAsync(2999)
  expect(attempt).not.toHaveBeenCalled()
  await vi.advanceTimersByTimeAsync(1)
  expect(attempt).toHaveBeenCalledWith(0)
  for (const delay of [2000, 4000, 8000, 15000]) await vi.advanceTimersByTimeAsync(delay)
  expect(attempt).toHaveBeenCalledTimes(5)
  scheduler.start('pair', attempt)
  await vi.advanceTimersByTimeAsync(60000)
  expect(attempt).toHaveBeenCalledTimes(5)
  scheduler.start('new-pair', attempt)
  await vi.advanceTimersByTimeAsync(3000)
  expect(attempt).toHaveBeenCalledTimes(6)
  scheduler.dispose()
})
it('cancels an outstanding retry and stops after success', async () => {
  vi.useFakeTimers()
  const scheduler = createRetryScheduler()
  const attempt = vi.fn().mockResolvedValue(true)
  scheduler.start('gone', attempt)
  scheduler.cancel('gone')
  await vi.advanceTimersByTimeAsync(3000)
  expect(attempt).not.toHaveBeenCalled()
  scheduler.start('live', attempt)
  await vi.advanceTimersByTimeAsync(90000)
  expect(attempt).toHaveBeenCalledOnce()
  scheduler.dispose()
  expect(vi.getTimerCount()).toBe(0)
})
