export type { ErrorKind, LobbyStatus } from './lobby/connectionController'
export { MAX_BOTS } from './lobby/host'
export { formatRoomCode } from './lobby/roomCode'
export { effectiveBots, type LobbyState } from './lobby/state'
export { MAX_RECONNECT_ATTEMPTS, type ReconnectEvent } from './session/reconnect'
export type { Intent, PeerInfo, Role, Seat, Where } from './types'
export { type ReconnectState, type UseLobby, useLobby } from './useLobby'
